GET http://localhost:8080/api/books

###

GET http://localhost:8080/api/books/633548e692df1eddeed375d6

###

POST http://localhost:8080/api/books
Content-Type: application/json

{
    "title": "我輩は猫である",
    "description": "夏目漱石",
    "comment": "面白い",
    "rating": 4
}

###

PATCH  http://localhost:8080/api/books/675a1e236e90f0d933685f6f
Content-Type: application/json

{
    "rating": 2
}


###

DELETE http://localhost:8080/api/books/6348cb2360bfbbb3b24b6ffc
